- name: maclandrol
  email: emmanuel.noutahi@hotmail.ca
  alternate_emails:
  - maclandrol@users.noreply.github.com
  num_commits: 0
  first_commit: 2021-04-06 11:53:10
- name: Cas Wognum
  email: caswognum@outlook.com
  aliases:
  - cwognum
  num_commits: 0
  first_commit: 2023-03-20 13:05:13
- name: Hadrien Mary
  email: hadrien.mary@gmail.com
  alternate_emails:
  - hadim@users.noreply.github.com
  num_commits: 0
  first_commit: 2023-03-21 12:50:42
- name: Therence
  email: 38595485+Therence1@users.noreply.github.com
  num_commits: 0
  first_commit: 2023-03-26 23:33:17
- name: Honore Hounwanou
  email: mercuryseries@gmail.com
  num_commits: 0
  first_commit: 2023-04-03 19:51:15
- name: Saurav Maheshkar
  github: SauravMaheshkar
  email: sauravvmaheshkar@gmail.com
  num_commits: 0
  first_commit: 2023-04-04 07:44:44
- name: rbyrne-momatx
  email: 113197924+rbyrne-momatx@users.noreply.github.com
  num_commits: 0
  first_commit: 2023-04-22 17:53:52
