name: Report a bug
description: Report a ðŸ›bugðŸ› in Molfeat
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >
        Before you go any further. Is this really a **ðŸ› bug**?

        If it's a question about how the API or how Molfeat works, have a look at our [Molfeat documentation](https://molfeat-docs.datamol.io/)
        or ask a question on our [Discussion board](https://github.com/datamol-io/molfeat/discussions).

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues and found nothing
          required: true

  - type: textarea
    attributes:
      label: Bug description
      description: A description of the ðŸ›bugðŸ›.
      placeholder: |
        A clear and concise description of what the bug is.

        Include steps to reproduce, the expected behaviour, and the actual behaviour.

        ```
        The error message you got, with the full traceback if available.
        ```

    validations:
      required: true

  - type: markdown
    attributes:
      value: "**Note: The rest of this form is optional, but filling it out may help us to provide better support.**"

  - type: textarea
    attributes:
      label: How to reproduce the bug
      description: >
        Provide steps and example code here.
        You can also paste a link to notebook, Google Colab or a Gist.
      placeholder: |
        ```python
        # Sample code to reproduce the problem
        ```
      render: python
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error messages and logs
      description: >
        Provide any error messages and/or logs
      placeholder: "# Copy the complete error messages and logs"
      value: |
        ```
        # Error messages and logs here please
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Environment
      description: |
        Please provide details about your environment (including the Molfeat version you are using) by filling the following information.
        You can add additional information if you think it is relevant.
      value: |
        <details>
          <summary>Current environment</summary>

        ```
        #- Molfeat version (e.g., 0.1.0):
        #- PyTorch Version (e.g., 1.10.0):
        #- RDKit version (e.g., 2022.09.5): 
        #- scikit-learn version (e.g.,  1.2.1): 
        #- OS (e.g., Linux):
        #- How you installed Molfeat (`conda`, `pip`, source):
        ```

        </details>
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "**Happy engineering!**"
